"""empty message
Revision ID: 4cc649431f09
Revises: 
Create Date: 2019-11-29 22:14:27.945843
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision = '4cc649431f09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
