"""empty message

Revision ID: 554fdcd76daf
Revises: 
Create Date: 2019-10-31 19:04:11.854717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554fdcd76daf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_meta', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
